name: Docker Image build and push for testing branches
on:
  workflow_dispatch:
  push:
    branches:
      - '!main'

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build and push created docker image to docker repository
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.repository }} #same as github username and repo name
          addLatest: false
          addTimestamp: true
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
