name: Docker Image build and push
on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build and push created docker image to docker repository
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: fmedery/docker-flask-gethostname
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
