name: Docker Image build and push
on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build and push created docker image to docker repository
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.repository }}
          # tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}






  # - uses: mr-smithers-excellent/docker-build-push@v6
  #   name: Build & push Docker image
  #   with:
  #     image: repo/image
  #     tags: v1, latest
  #     registry: registry-url.io
  #     dockerfile: Dockerfile.ci
  #     username: ${{ secrets.DOCKER_USERNAME }}
  #     password: ${{ secrets.DOCKER_PASSWORD }}