name: Docker Image build and push

on:
  push:
    branches: [ "main" ]

jobs:
  building-containers:
    name: Build containers
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Create Tag for Docker Image
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ github.repository }}:latest,${{ github.repository }}:${{ steps.vars.outputs.sha_short }}